### ISSUE TITLE
Policies

### ISSUE THREAD

**Issue by hexylena** [ubinfie/ubinfie.github.io#2]
@lskatz you seem like the person to make high level decisions :)

- New posts should be approved by one of the editorial team? Or more people?
- who is on the editorial board (im calling it this because it looks nicer for everyone's CVs. we used to call them "moderators" or "maintainers" in another project but rebranded)
- how do they get added or request to join or are they nominated or literally just anyone who volunteere
- What should be the minimum number to ensure the burden is low on volunteers
- Rotating schedule? or by topic area? (I am admittedly much more qualified on packaging and infra and phages than e.g. metagenomics)
- preferred code of conduct? (does the chat have one?)
- ... more thoughts later

**Comment by karinlag** [comment]
Regarding editors (I like the term here btw!), how about we make it simple? The people adding things suggest 2 people to review the thing. If someone feels unqualified, they either ping it back to the author, or suggests someone else. 

I am thinking we might separate between organizers and editors? The editors could maybe be anyone signed up for this repo, but maybe there should be a core group that checks to see that the reviewers chosen for a post make sense and is known to the community?

**Comment by lskatz** [comment]
What about just one review from an Editor especially since we all trust each other? Can you set it up that way for now? That a pull request just requires one trusted reviewer?

**Comment by lskatz** [comment]
Yes I think make a core group of editors. Maybe just the list of owners but you use your best judgement.

**Comment by hexylena** [comment]
from @ammaraziz

> I think we have to agree upon some basic rules about screenshots, quoting comments, and referencing this slack. I suggest that for quoting/screenshooting chats, all names must be redacted unless explicitly agreed upon by person quoted or screenshot.

and

> On the topic of posts, I think posts should not be a huge dump of screenshots/quotes. The blog post should contain some preamble about what triggered the discussion, link to relevant papers, tools discussed. etc.

which everyone agreed with.

**Comment by hexylena** [comment]
> Maybe just the list of owners but you use your best judgement.

Ok, we'll start with that and go from there!
