### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by pmenzel** [ubinfie/ubinfie.github.io#24]
Currently, footnotes just show up at the end of the text before the references, which looks weird..

Example from `contributing.md`
![grafik](https://github.com/ubinfie/ubinfie.github.io/assets/1469600/6c300d7a-206c-42cb-8e59-0d11706a2b57)

Maybe put an `<hr>` before them if possible? 

Anyways, footnotes are weird on websites.. Is there any benefit of having them at all?

**Comment by hexylena** [comment]
yeah you're not wrong they're not often useful. They're not a feature that was enabled, I dont think they can be disabled, but we can of course remove the documentation of them

**Comment by pmenzel** [comment]
It doesn't seem possible to add an `<hr/>` before the footnotes using the templates in `_layout`, as they are contained in the `content` variable already.

Then I would just remove the docs as you mentioned.
