### ISSUE TITLE
contribution links in README.md don't work

### ISSUE THREAD

**Issue by pmenzel** [ubinfie/ubinfie.github.io#41]
the links behind the symbols 📖 👀 etc. point to https://github.com/ubinfie/ubinfie/... but should point to https://github.com/ubinfie/ubinfie.github.io/...

I believe this can be fixed by changing the projectName [here ](https://github.com/ubinfie/ubinfie.github.io/blob/ac802dbd8a39ab6c0a26e7c033ebd5b5021a74eb/.all-contributorsrc#L2C19-L2C26) from `ubinfie` to `ubinfie.github.io` 

@hexylena ?

**Comment by hexylena** [comment]
yes, you would be correct.
